[package]
name = "unicode_bidi_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "unicode_bidi_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
unicode-bidi = "0.3.13"
